TARGET=calc_momentum

FEDRALIBS := -lEIO -lEdb -lEbase -lEdr -lScan -lAlignment -lEmath -lEphys -lvt -lDataConversion -lEDA -lShower -lScan -lMLP -lSpectrum

LIBS := ../../include
SRC := ../../src/*.cpp

$TARGET: $(TARGET).cpp
	g++ $(TARGET).cpp -g3 -w -I$(LIBS) $(SRC)  `root-config --cflags` -I$(FEDRA_ROOT)/include -L$(FEDRA_ROOT)/lib  $(FEDRALIBS) `root-config --libs` `root-config --glibs` `root-config --evelibs` -o $(TARGET)

clean:
	$(RM) $(TARGET)
